version: "3.7"

services: 

  ssh:
    image: vudinhquang/sshserver
    ports: 
      - 22:22
    environment: 
      sshuser: sshuser
      password: 1234567
    volumes:
      - /home/data1/:/data/
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role==manager

  samba:
    image: vudinhquang/samba
    ports: 
      - 139:139
      - 145:145
    environment: 
      smbuser: smbuser
      password: 1234567
    volumes:
      - /home/data/:/data/
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role==manager

  service1:
    image: vudinhquang/swarmtest:node
    networks: 
      - net1
    ports: 
      - 8085:8085
    volumes: 
      - vol1:/d1/
      - vol2:/d2/
      - vol3:/d3/
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.5"
          memory: 150MB
        reservations:
          cpus: "0.25"
          memory: 50MB
      restart_policy:
        condition: on-failure

  service2:
    image: vudinhquang/swarmtest:php
    networks: 
      - net2
    ports: 
      - 8086:8085
    volumes: 
      - vol1:/d1/
      - vol2:/d2/
      - vol3:/d3/
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.5"
          memory: 150MB
        reservations:
          cpus: "0.25"
          memory: 50MB
      restart_policy:
        condition: on-failure

networks: 
  net1:
  net2:
    driver: overlay
    name: www-net2  

volumes: 
  vol1:
    driver: local
    name: v1
    # driver_opts: 
    #   type: none
    #   device: "/home/"
    #   o: bind
  vol2:
    driver: local
    name: v2
    driver_opts: 
      type: cifs
      device: //34.235.166.222/data
      o: "username=smbuser,password=1234567,file_mode=0777,dir_mode=0777"
  vol3:
    driver: vieux/sshfs
    name: v3
    driver_opts: 
      sshcmd: "sshuser@34.235.166.222:/data"
      port: 22
      # IdentityFile: //
      password: 1234567
      allow_other: ""
