version: '3'
services:                                                                                       
  web:                                                                                          
      build: .
      command: ["/usr/sbin/httpd","-D","FOREGROUND"] 
      volumes: 
        - ./source:/var/www/html          
      ports:                                                                                      
        - "80:80"
